export const FETCH_RECIPES_PENDING = "FETCH_RECIPES_PENDING"
export const FETCH_RECIPES_REJECTED = "FETCH_RECIPES_REJECTED"
export const FETCH_RECIPES_FULFILLED = "FETCH_RECIPES_FULFILLED"
export const FETCH_RECIPES = "FETCH_RECIPES"
