import fridgeLoadRequest from '../api/signUpAPI'

export const fridgeActions = {
  FRIDGE_LOAD_PENDING: "FRIDGE_LOAD_PENDING",
  FRIDGE_LOAD_REJECTED: "FRIDGE_LOAD_REJECTED",
  FRIDGE_LOAD_FULFILLED: "FRIDGE_LOAD_FULFILLED",
  FRIDGE_LOAD: "FRIDGE_LOAD",

  FRIDGE_ITEM_REMOVE_PENDING: "FRIDGE_ITEM_REMOVE_PENDING",
  FRIDGE_ITEM_REMOVE_REJECTED: "FRIDGE_ITEM_REMOVE_REJECTED",
  FRIDGE_ITEM_REMOVE_FULFILLED: "FRIDGE_ITEM_REMOVE_FULFILLED",
  FRIDGE_ITEM_REMOVE: "FRIDGE_ITEM_REMOVE",

  FRIDGE_ITEM_ADD_PENDING: "FRIDGE_ITEM_ADD_PENDING",
  FRIDGE_ITEM_ADD_REJECTED: "FRIDGE_ITEM_ADD_REJECTED",
  FRIDGE_ITEM_ADD_FULFILLED: "FRIDGE_ITEM_ADD_FULFILLED",
  FRIDGE_ITEM_ADD: "FRIDGE_ITEM_ADD",

  fridgeLoad: ({ email, password, phone }) => ({
    type: fridgeActions.FRIDGE_LOAD,
    payload: fridgeLoadRequest({ email, password, phone })
  })
}
